project:
  type: website
  output-dir: docs

website:
  title: "Mukhil Guna"
  navbar:
    right:
      - href: index.qmd
        text: Landing Page
      - about.qmd
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

